/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busquedas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;

/**
 *
 * @author melis
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnDesordenar = new javax.swing.JButton();
        txtNumero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        botonOrdenar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        maxPasos = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        heuristica = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 50, 20, 30);

        jLabel2.setText("2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 100, 20, 30);

        jLabel3.setText("3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 180, 20, 30);

        jLabel4.setText("4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(220, 220, 20, 30);

        jLabel5.setText("5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 220, 20, 30);

        jLabel6.setText("6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 170, 30, 30);

        jLabel7.setText("7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 100, 20, 30);

        jLabel8.setText("8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(150, 50, 20, 30);

        jLabel9.setText("9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 120, 30, 30);

        jLabel10.setText("10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(200, 160, 30, 30);

        jLabel11.setText("11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(160, 160, 30, 30);

        jLabel12.setText(" ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(160, 120, 30, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura.PNG"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, -4, 340, 304);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura.PNG"))); // NOI18N
        jLabel16.setText("jLabel13");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, -4, 340, 304);

        btnDesordenar.setText("Desordenar");
        btnDesordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesordenarActionPerformed(evt);
            }
        });

        txtNumero.setText("1");

        jLabel14.setText("Ingrese el numero de");

        jLabel15.setText("veces que desea desordenar");

        botonOrdenar.setText("Ordenar");
        botonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenarActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(5);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("G(n) será un número de pasos máximos que ingresará el usuario antes de empezar (ir contando en cada salto cuántos llevan).");
        jScrollPane1.setViewportView(jTextArea1);

        maxPasos.setText("100");

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("H(n) será el uso de los dos tipos de heurística:\n0: Manhattan: sumatoria de los saltos que le faltan a todas las piezas para llegar a su lugar\n1: Casillas fuera de lugar: sumatoria del número de piezas que no están en su lugar");
        jScrollPane2.setViewportView(jTextArea2);

        heuristica.setText("0");

        consola.setEditable(false);
        consola.setColumns(20);
        consola.setRows(5);
        jScrollPane3.setViewportView(consola);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDesordenar)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonOrdenar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(maxPasos, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(heuristica))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDesordenar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(maxPasos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(heuristica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonOrdenar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesordenarActionPerformed
        Thread thread;
        thread = new Thread() {
            public void run() {
                ArrayList<String> numeros = new ArrayList<>();
                    numeros.add("1");
                    numeros.add("2");
                    numeros.add("3");
                    numeros.add("4");
                    numeros.add("5");
                    numeros.add("6");
                    numeros.add("7");
                    numeros.add("8");
                    numeros.add("9");
                    numeros.add("10");
                    numeros.add("11");
                    numeros.add(" ");
                    
                for (int i = 0; i < Integer.parseInt(txtNumero.getText()); i++) {
                    long seed = System.nanoTime();
                    Collections.shuffle(numeros, new Random(seed));
                    
                    jLabel1.setText(numeros.get(0));
                    jLabel2.setText(numeros.get(1));
                    jLabel3.setText(numeros.get(2));
                    jLabel4.setText(numeros.get(3));
                    jLabel5.setText(numeros.get(4));
                    jLabel6.setText(numeros.get(5));
                    jLabel7.setText(numeros.get(6));
                    jLabel8.setText(numeros.get(7));
                    jLabel9.setText(numeros.get(8));
                    jLabel10.setText(numeros.get(9));
                    jLabel11.setText(numeros.get(10));
                    jLabel12.setText(numeros.get(11));
                    
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        thread.start();
    }//GEN-LAST:event_btnDesordenarActionPerformed

    private void botonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenarActionPerformed
        try {
            PrintWriter writer = new PrintWriter("parametros.txt", "UTF-8");
            writer.println((jLabel1.getText().equalsIgnoreCase(" ")) ? "12" : jLabel1.getText());
            writer.println((jLabel2.getText().equalsIgnoreCase(" ")) ? "12" : jLabel2.getText());
            writer.println((jLabel3.getText().equalsIgnoreCase(" ")) ? "12" : jLabel3.getText());
            writer.println((jLabel4.getText().equalsIgnoreCase(" ")) ? "12" : jLabel4.getText());
            writer.println((jLabel5.getText().equalsIgnoreCase(" ")) ? "12" : jLabel5.getText());
            writer.println((jLabel6.getText().equalsIgnoreCase(" ")) ? "12" : jLabel6.getText());
            writer.println((jLabel7.getText().equalsIgnoreCase(" ")) ? "12" : jLabel7.getText());
            writer.println((jLabel8.getText().equalsIgnoreCase(" ")) ? "12" : jLabel8.getText());
            writer.println((jLabel9.getText().equalsIgnoreCase(" ")) ? "12" : jLabel9.getText());
            writer.println((jLabel10.getText().equalsIgnoreCase(" ")) ? "12" : jLabel10.getText());
            writer.println((jLabel11.getText().equalsIgnoreCase(" ")) ? "12" : jLabel11.getText());
            writer.println((jLabel12.getText().equalsIgnoreCase(" ")) ? "12" : jLabel12.getText());
            writer.println(maxPasos.getText());
            writer.println(heuristica.getText());

            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Process p;
        String ret = "";
        try {
            p = Runtime.getRuntime().exec("python puzzlesolver.py");
            BufferedReader in = new BufferedReader(new InputStreamReader(p.getInputStream()));
            ret = in.readLine();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (ret.equalsIgnoreCase("No se encontro solucion factible")) {
            JOptionPane.showMessageDialog(null, ret);
        } else {
            Thread thread = new Thread() {
                public void run() {
                    try {
                        /*File f = new File("resultado.txt");
                        while(!f.exists()) { 
                            Thread.sleep(1000);
                        }*/
                        
                        File file = new File("resultado.txt");
                        FileReader fileReader = new FileReader(file);
                        BufferedReader bufferedReader = new BufferedReader(fileReader);
                        String line;
                        while ((line = bufferedReader.readLine()) != null) {
                                consola.setText(line + "\n" + consola.getText());
                                String nuevoEstado = line.substring(line.indexOf("[")+1, line.indexOf("]"));
                                String[] nuevaConfig = nuevoEstado.split(" ");
                                
                                int k;
                                for (k = 0; k < 16; k++) {
                                    if (nuevaConfig[k].equalsIgnoreCase("12"))
                                        nuevaConfig[k] = " ";
                                }
                                
                                Thread.sleep(1000);
                                
                                jLabel1.setText(nuevaConfig[2]);
                                jLabel2.setText(nuevaConfig[7]);
                                jLabel3.setText(nuevaConfig[11]);
                                jLabel4.setText(nuevaConfig[14]);
                                jLabel5.setText(nuevaConfig[13]);
                                jLabel6.setText(nuevaConfig[8]);
                                jLabel7.setText(nuevaConfig[4]);
                                jLabel8.setText(nuevaConfig[1]);
                                jLabel9.setText(nuevaConfig[6]);
                                jLabel10.setText(nuevaConfig[10]);
                                jLabel11.setText(nuevaConfig[9]);
                                jLabel12.setText(nuevaConfig[5]);
                        }
                        fileReader.close();
                        
                        File arc = new File("resultado.txt");
        	
                        file.delete();
                    } catch (IOException e) {
                            e.printStackTrace();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Busquedas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            };
            thread.start();
        }
    }//GEN-LAST:event_botonOrdenarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonOrdenar;
    private javax.swing.JButton btnDesordenar;
    private javax.swing.JTextArea consola;
    private javax.swing.JTextField heuristica;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField maxPasos;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
